name: dart_class_mapper
description: Biblioteca leve para mapear classes e JSON em Dart. Ideal para conversões entre entidades, DTOs e objetos JSON com uma API simples e reutilizável.

version: 1.0.2
repository: https://github.com/LucassMateus/dart_class_mapper
topics:
  - class-mapper
  - mappings
  - automapper
  - object-transform
  - dart

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
