name: dart_class_mapper
description: Package para fazer mapeamento entre classes.
version: 1.0.0
repository: https://github.com/LucassMateus/dart_class_mapper

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
