name: dart_class_mapper
description:
  O Dart Class Mapper é uma biblioteca leve e intuitiva para facilitar o mapeamento entre diferentes classes em Dart.
  Ideal para cenários como conversões entre entidades e DTOs, este package ajuda a reduzir repetição de código, melhora
  a organização e promove reutilização através de uma API simples baseada em funções como `CreateMap` e `GetMapper`.

version: 1.0.1
repository: https://github.com/LucassMateus/dart_class_mapper
topics:
  - class-mapper
  - mappings
  - automapper
  - object-transform
  - dart

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
