name: dart_class_mapper
description: Lightweight library for mapping classes in Dart. Ideal for converting between entities and DTOs objects with a simple and reusable API.

version: 1.2.1

repository: https://github.com/LucassMateus/dart_class_mapper
topics:
  - class-mapper
  - mappings
  - automapper
  - object-transform
  - mapper

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
