name: Create tag and publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  check_publish_warnings:
    runs-on: ubuntu-latest
    steps:
      - name: Check Publish Warnings
        uses: dart pub publish --dry-run

  create_tag:
    name: Create Git Tag from pubspec.yaml
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Get pubspec version
        id: get_version
        run: |
          VERSION=$(dart pub pubspec | grep '^version:' | awk '{ print $2 }')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag "v${{ steps.get_version.outputs.VERSION }}"
          git push origin "v${{ steps.get_version.outputs.VERSION }}"

  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Publish
        run: dart pub publish --force
